### ISSUE TITLE
Serve the model 

### ISSUE THREAD

**Issue by tsaoyu** [deeplearninc/relaax#99]
I have created and trained my model on my own environment. My question is how to serve the trained model with relaax? Is there a CLI option or similar? Many thanks.

**Comment by 4SkyNet** [comment]
Hi @tsaoyu! 

Your `model` should be `relaax` compatible to use it further.
We use standard `tensorflow` checkpoints to store & restore the training process
(you can find respective folders `checkpoints && metrics` when training is initiated),
since that, if you perform training with `not-relaax` (at least tensor compatible) model
you should transfer the weight by `hand` with your own procedure.

p.s> sorry for some delay with reply

**Comment by tsaoyu** [comment]
@4SkyNet Many thanks! I management to run the model by turn off the 'exploit' feature. I will see if I could manually transfer the weights later. 
Cheers
